/* Blush Tiny Blossoms — site script. Data comes from /assets/data.js (window.BLUSH), generated by build.py. */
(function () {
  const { shop: SHOP, looks: LOOKS } = window.BLUSH;
  const ROOT = new URL("..", document.currentScript.src).href; // site root, wherever the site is hosted
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const esc = s => String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const fullName = l => l.name + (l.variant ? " · " + l.variant : "");
  const money = n => SHOP.currency + Number(n).toLocaleString("en-IN");
  const priceOf = (l, size) => (l.priceBySize && size ? l.priceBySize[size] : null) || null;
  const fromPrice = l => (l.priceBySize ? "From " + money(Math.min(...Object.values(l.priceBySize))) : "Price on request");
  const priceText = (l, size) => (priceOf(l, size) ? money(priceOf(l, size)) : fromPrice(l));
  const igDM = "https://ig.me/m/" + SHOP.instagram;
  const waLink = text => "https://wa.me/" + SHOP.whatsapp + (text ? "?text=" + encodeURIComponent(text) : "");

  /* ── Bag: the one place that knows how items are stored. Swap this for a real cart API when the store opens. ── */
  const KEY = "blush.bag.v1";
  let memory = [];
  const Bag = {
    read() {
      try { const v = JSON.parse(localStorage.getItem(KEY) || "[]"); memory = Array.isArray(v) ? v.filter(i => LOOKS[i.id]) : []; } catch (e) {}
      return memory;
    },
    write(items) {
      memory = items;
      try { localStorage.setItem(KEY, JSON.stringify(items)); } catch (e) {}
      paintCount();
    },
    add(id, size) {
      const items = Bag.read();
      const hit = items.find(i => i.id === id && i.size === size);
      if (hit) hit.qty = Math.min(9, hit.qty + 1); else items.push({ id, size, qty: 1 });
      Bag.write(items);
    },
    count() { return Bag.read().reduce((n, i) => n + i.qty, 0); },
    message(items) {
      const lines = items.map(i => { const p = priceOf(LOOKS[i.id], i.size); return "• " + fullName(LOOKS[i.id]) + (i.size ? ", size " + i.size : "") + (i.qty > 1 ? " × " + i.qty : "") + (p ? " (" + money(p) + (i.qty > 1 ? " each" : "") + ")" : ""); });
      const sub = Bag.subtotal(items);
      return "Hi Blush! I'd like to order:\n" + lines.join("\n") + (sub !== null ? "\nTotal: " + money(sub) : "") + "\nPlease confirm availability and delivery.";
    },
    subtotal(items) { return items.every(i => priceOf(LOOKS[i.id], i.size)) ? items.reduce((n, i) => n + priceOf(LOOKS[i.id], i.size) * i.qty, 0) : null; }
  };
  function paintCount() {
    const n = memory.reduce((a, i) => a + i.qty, 0);
    $$(".bag-count").forEach(el => { el.textContent = n; el.dataset.n = n; });
    $$(".bag-link").forEach(el => el.setAttribute("aria-label", "Enquiry bag, " + n + (n === 1 ? " item" : " items")));
  }
  Bag.read(); paintCount();

  async function copy(text, btn, fallbackEl) {
    try { await navigator.clipboard.writeText(text); btn.textContent = "Copied"; }
    catch (e) {
      if (fallbackEl) { const r = document.createRange(); r.selectNodeContents(fallbackEl); const s = getSelection(); s.removeAllRanges(); s.addRange(r); }
      btn.textContent = "Selected, now copy";
    }
    setTimeout(() => (btn.textContent = btn.dataset.label || "Copy message"), 2400);
  }

  /* ── Header ── */
  const menuBtn = $(".menu-btn"), menu = $("#menu");
  if (menuBtn) {
    menuBtn.addEventListener("click", () => {
      const open = menu.classList.toggle("open");
      menuBtn.setAttribute("aria-expanded", open);
    });
    document.addEventListener("keydown", e => { if (e.key === "Escape") { menu.classList.remove("open"); menuBtn.setAttribute("aria-expanded", "false"); } });
  }
  if (SHOP.whatsapp) $$("[data-wa]").forEach(el => { el.hidden = false; const a = el.matches("a") ? el : $("a", el); if (a && !a.dataset.msg) a.href = waLink(""); });

  /* ── Collection filters ── */
  const filters = $("#filters");
  if (filters) {
    const cards = $$("#grid .card");
    const setFilter = (k, push) => {
      if (!$$(".filter", filters).some(b => b.dataset.key === k)) k = "all";
      $$(".filter", filters).forEach(b => b.setAttribute("aria-pressed", b.dataset.key === k));
      cards.forEach(c => (c.hidden = !(k === "all" || c.dataset.cat.split(" ").includes(k))));
      const n = cards.filter(c => !c.hidden).length, cnt = $("#count"); if (cnt) cnt.textContent = n + (n === 1 ? " look" : " looks");
      if (push) history.replaceState(null, "", k === "all" ? location.pathname : "?show=" + k);
    };
    filters.addEventListener("click", e => { const b = e.target.closest(".filter"); if (b) setFilter(b.dataset.key, true); });
    setFilter(new URLSearchParams(location.search).get("show") || "all", false);
  }

  /* ── Look page ── */
  const lookEl = $("[data-look]");
  if (lookEl) {
    const l = LOOKS[lookEl.dataset.look];
    let size = null;
    const msgEl = $("#look-msg"), buy = $("#look-buy"), added = $("#look-added"), sizes = $("#look-sizes"), chosen = $("#size-chosen");
    const mrpOf = s => (l.mrpBySize && s ? l.mrpBySize[s] : null);
    const message = () => "Hi Blush! I'd like to order " + fullName(l) + (size ? " in size " + size : "") + (priceOf(l, size) ? " (" + money(priceOf(l, size)) + ")" : "") + ".\n" + location.href.split("?")[0] + "\nPlease confirm availability" + (l.priceBySize ? "." : " and share the price.");
    const refresh = () => {
      if (msgEl) msgEl.textContent = message();
      if (SHOP.whatsapp && buy) buy.href = waLink(message());
    };
    const paintPrice = () => {
      $("#look-price").textContent = priceText(l, size);
      const m = $("#look-mrp"), sv = $("#look-save");
      const mp = size ? mrpOf(size) : (l.mrpBySize ? Math.min(...Object.values(l.mrpBySize)) : null);
      const pp = size ? priceOf(l, size) : (l.priceBySize ? Math.min(...Object.values(l.priceBySize)) : null);
      if (m) { m.hidden = !(mp && pp && mp > pp); if (mp) m.textContent = money(mp); }
      if (sv && mp && pp) sv.textContent = "Sale · Save " + Math.round(100 * (1 - pp / mp)) + "%";
    };
    if (sizes) sizes.addEventListener("click", e => {
      const b = e.target.closest("button"); if (!b || b.disabled) return;
      size = b.textContent; $$("button", sizes).forEach(x => x.setAttribute("aria-pressed", x === b));
      if (chosen) chosen.textContent = size;
      added.textContent = ""; paintPrice(); refresh();
    });
    const needSize = () => { if (l.sizes.length && !size) { added.textContent = "Please choose a size first."; sizes.querySelector("button:not(:disabled)")?.focus(); return true; } return false; };
    $("#look-add").addEventListener("click", () => {
      if (needSize()) return;
      Bag.add(l.id, size);
      added.innerHTML = "Added to your bag. <a href=\"" + ROOT + "bag\">View bag</a>";
    });
    if (buy && SHOP.whatsapp) buy.addEventListener("click", e => { if (needSize()) e.preventDefault(); });
    const lc = $("#look-copy"); if (lc) lc.addEventListener("click", e => copy(message(), e.currentTarget, msgEl));
    const cl = $("#copy-link");
    if (cl) cl.addEventListener("click", async () => {
      const out = $("#link-copied");
      try { await navigator.clipboard.writeText(cl.dataset.url); out.textContent = "Link copied"; } catch (e) { out.textContent = cl.dataset.url; }
      setTimeout(() => (out.textContent = ""), 2600);
    });
    refresh();

    /* gallery: swipe/scroll track, thumbnails, arrows, lightbox */
    const track = $("#track");
    if (track) {
      const slides = $$(".slide", track), thumbs = $$(".thumbs button");
      let cur = 0;
      const go = i => { cur = (i + slides.length) % slides.length; track.scrollTo({ left: track.clientWidth * cur }); };
      const mark = () => {
        cur = Math.round(track.scrollLeft / Math.max(1, track.clientWidth));
        thumbs.forEach((t, i) => t.setAttribute("aria-selected", i === cur));
      };
      track.addEventListener("scroll", () => requestAnimationFrame(mark), { passive: true });
      thumbs.forEach((t, i) => t.addEventListener("click", () => go(i)));
      $$(".stage .nav-arrow").forEach(b => b.addEventListener("click", () => go(cur + (b.classList.contains("next") ? 1 : -1))));
      const lb = $("#lightbox"), lbImg = $("#lb-img");
      const full = i => { const im = $("img", slides[i]); return im.srcset.split(",").map(x => x.trim().split(" ")[0]).pop(); };
      const show = i => { cur = (i + slides.length) % slides.length; lbImg.src = full(cur); lbImg.alt = $("img", slides[cur]).alt; };
      if (lb && lb.showModal) {
        slides.forEach((s, i) => s.addEventListener("click", () => { show(i); lb.showModal(); }));
        $$("[data-lb]", lb).forEach(b => b.addEventListener("click", () => show(cur + +b.dataset.lb)));
        lbImg.addEventListener("click", () => lb.close());
        lb.addEventListener("close", () => go(cur));
        lb.addEventListener("keydown", e => { if (e.key === "ArrowRight") show(cur + 1); if (e.key === "ArrowLeft") show(cur - 1); });
      }
    }
  }

  /* size guide dialog + cm/in switch (look pages and the size guide page) */
  $$("[data-open]").forEach(b => b.addEventListener("click", () => { const d = document.getElementById(b.dataset.open); if (d && d.showModal) d.showModal(); }));
  $$("dialog").forEach(d => d.addEventListener("click", e => { if (e.target === d) d.close(); }));
  $$(".chart").forEach(c => c.addEventListener("click", e => {
    const b = e.target.closest("[data-u]"); if (!b) return;
    $$(".chart").forEach(x => { x.dataset.unit = b.dataset.u; $$("[data-u]", x).forEach(y => y.setAttribute("aria-pressed", y.dataset.u === b.dataset.u)); });
  }));

  /* "You may also like" rail arrows */
  const rail = $("#rail");
  if (rail) $$("[data-rail]").forEach(b => b.addEventListener("click", () => rail.scrollBy({ left: +b.dataset.rail * rail.clientWidth * 0.8 })));

  /* FAQ: open the question group that a link points to, highlight the section in view */
  const faqNav = $(".faq-nav:not(.toc)");
  if (faqNav) {
    const links = $$("a", faqNav);
    const io = new IntersectionObserver(es => es.forEach(en => { if (en.isIntersecting) links.forEach(a => a.classList.toggle("on", a.hash === "#" + en.target.id)); }), { rootMargin: "-30% 0px -60% 0px" });
    $$(".faq-sec").forEach(s => io.observe(s));
  }

  /* ── Bag page ── */
  const bagRoot = $("#bag-root");
  if (bagRoot) {
    const render = () => {
      const items = Bag.read();
      if (!items.length) {
        bagRoot.innerHTML = '<div class="empty"><svg class="blossom" viewBox="0 0 24 24" fill="currentColor" style="color:var(--rose)" aria-hidden="true"><circle cx="12" cy="5.5" r="3.4"/><circle cx="18.2" cy="10" r="3.4"/><circle cx="15.8" cy="17.2" r="3.4"/><circle cx="8.2" cy="17.2" r="3.4"/><circle cx="5.8" cy="10" r="3.4"/></svg><p class="lede">Your enquiry bag is empty.</p><a class="btn" href="' + ROOT + 'collection">View the collection</a></div>';
        return;
      }
      const msg = Bag.message(items), sub = Bag.subtotal(items), n = items.reduce((a, i) => a + i.qty, 0);
      const storeReady = SHOP.mode === "store" && SHOP.checkoutUrl && sub !== null;
      bagRoot.innerHTML = '<div class="bag"><div class="bag-items">' + items.map((i, x) => {
        const l = LOOKS[i.id];
        return '<div class="bag-item"><a class="arch" href="' + ROOT + 'looks/' + l.id + '"><img src="' + ROOT + 'img/' + l.id + '-480.webp" alt="" style="object-position:' + l.pos + '"></a>' +
          '<div><h3><a href="' + ROOT + 'looks/' + l.id + '">' + esc(fullName(l)) + '</a></h3><p class="meta">' + (i.size ? "Size " + esc(i.size) : "Size on request") + '</p><p class="price">' + priceText(l, i.size) + '</p></div>' +
          '<div class="bag-ctl"><div class="qty"><button type="button" data-act="dec" data-x="' + x + '" aria-label="One fewer">–</button><span aria-live="polite">' + i.qty + '</span><button type="button" data-act="inc" data-x="' + x + '" aria-label="One more">+</button></div>' +
          '<button type="button" class="linkbtn" data-act="del" data-x="' + x + '">Remove</button></div></div>';
      }).join("") + '</div>' +
        '<aside class="preview"><span class="eyebrow">Your enquiry</span>' +
        '<div class="sum-row"><span>Pieces</span><b>' + n + '</b></div>' +
        '<div class="sum-row"><span>' + (sub !== null ? "Subtotal" : "Price") + '</span><b>' + (sub !== null ? money(sub) : "Confirmed on message") + '</b></div>' +
        '<div class="msg" id="bag-msg">' + esc(msg) + '</div>' +
        '<div class="dlg-cta">' +
        (storeReady ? '<a class="btn" href="' + esc(SHOP.checkoutUrl) + '">Checkout</a>' : "") +
        (SHOP.whatsapp ? '<a class="btn' + (storeReady ? " ghost" : "") + '" href="' + waLink(msg) + '" target="_blank" rel="noopener">Send on WhatsApp</a>' : "") +
        '<button class="btn' + (storeReady || SHOP.whatsapp ? " ghost" : "") + '" type="button" id="bag-copy" data-label="Copy message">Copy message</button>' +
        '<a class="btn ghost" href="' + igDM + '" target="_blank" rel="noopener">Open Instagram chat</a>' +
        '</div><p class="hint">' + (SHOP.whatsapp ? "WhatsApp opens with the message ready. For Instagram, copy the message and paste it in our chat." : "Copy the message, then paste it in our Instagram chat.") + ' We reply to confirm availability and delivery.</p></aside></div>';
    };
    bagRoot.addEventListener("click", e => {
      const b = e.target.closest("[data-act]");
      if (b) {
        const items = Bag.read(), i = items[+b.dataset.x]; if (!i) return;
        if (b.dataset.act === "inc") i.qty = Math.min(9, i.qty + 1);
        if (b.dataset.act === "dec") i.qty -= 1;
        if (b.dataset.act === "del" || i.qty < 1) items.splice(+b.dataset.x, 1);
        Bag.write(items); render(); return;
      }
      if (e.target.id === "bag-copy") copy(Bag.message(Bag.read()), e.target, $("#bag-msg"));
    });
    render();
  }

  /* ── Contact composer ── */
  const form = $("#enquiry");
  if (form) {
    const out = $("#enq-msg"), wa = $("#enq-wa");
    const pre = new URLSearchParams(location.search).get("look");
    if (pre && LOOKS[pre]) form.look.value = pre;
    const message = () => {
      const f = form, l = LOOKS[f.look.value], parts = [];
      parts.push("Hi Blush!" + (f.name.value.trim() ? " This is " + f.name.value.trim() + "." : ""));
      parts.push(l ? "I'd like to enquire about " + fullName(l) + (f.size.value ? " in size " + f.size.value : "") + "." : "I'd like to enquire about your festive collection.");
      if (f.age.value.trim()) parts.push("My child is " + f.age.value.trim() + ".");
      if (f.date.value) parts.push("We need it by " + new Date(f.date.value + "T00:00").toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }) + ".");
      if (f.note.value.trim()) parts.push(f.note.value.trim());
      if (l && priceOf(l, f.size.value)) parts.push("The price shown is " + money(priceOf(l, f.size.value)) + ".");
      parts.push("Please confirm availability.");
      return parts.join(" ");
    };
    const refresh = () => { out.textContent = message(); if (SHOP.whatsapp) { wa.hidden = false; wa.href = waLink(message()); } };
    form.addEventListener("input", refresh);
    form.addEventListener("submit", e => e.preventDefault());
    $("#enq-copy").addEventListener("click", e => copy(message(), e.currentTarget, out));
    refresh();
  }
})();
