/* Blush Tiny Blossoms — site script. Data comes from /assets/data.js (window.BLUSH), generated by build.py. */
(function () {
  const { shop: SHOP, looks: LOOKS } = window.BLUSH;
  const $ = (s, r = document) => r.querySelector(s);
  const $$ = (s, r = document) => [...r.querySelectorAll(s)];
  const esc = s => String(s).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const fullName = l => l.name + (l.variant ? " · " + l.variant : "");
  const money = n => SHOP.currency + Number(n).toLocaleString("en-IN");
  const priceText = l => (l.price ? money(l.price) : "Price on request");
  const igDM = "https://ig.me/m/" + SHOP.instagram;
  const waLink = text => "https://wa.me/" + SHOP.whatsapp + (text ? "?text=" + encodeURIComponent(text) : "");

  /* ── Bag: the one place that knows how items are stored. Swap this for a real cart API when the store opens. ── */
  const KEY = "blush.bag.v1";
  let memory = [];
  const Bag = {
    read() {
      try { const v = JSON.parse(localStorage.getItem(KEY) || "[]"); memory = Array.isArray(v) ? v.filter(i => LOOKS[i.id]) : []; } catch (e) {}
      return memory;
    },
    write(items) {
      memory = items;
      try { localStorage.setItem(KEY, JSON.stringify(items)); } catch (e) {}
      paintCount();
    },
    add(id, size) {
      const items = Bag.read();
      const hit = items.find(i => i.id === id && i.size === size);
      if (hit) hit.qty = Math.min(9, hit.qty + 1); else items.push({ id, size, qty: 1 });
      Bag.write(items);
    },
    count() { return Bag.read().reduce((n, i) => n + i.qty, 0); },
    message(items) {
      const lines = items.map(i => "• " + fullName(LOOKS[i.id]) + (i.size ? ", size " + i.size : "") + (i.qty > 1 ? " × " + i.qty : ""));
      return "Hi Blush! I'd like to enquire about:\n" + lines.join("\n") + "\nPlease share the price and availability.";
    },
    subtotal(items) { return items.every(i => LOOKS[i.id].price) ? items.reduce((n, i) => n + LOOKS[i.id].price * i.qty, 0) : null; }
  };
  function paintCount() {
    const n = memory.reduce((a, i) => a + i.qty, 0);
    $$(".bag-count").forEach(el => { el.textContent = n; el.dataset.n = n; });
    $$(".bag-link").forEach(el => el.setAttribute("aria-label", "Enquiry bag, " + n + (n === 1 ? " item" : " items")));
  }
  Bag.read(); paintCount();

  async function copy(text, btn, fallbackEl) {
    try { await navigator.clipboard.writeText(text); btn.textContent = "Copied"; }
    catch (e) {
      if (fallbackEl) { const r = document.createRange(); r.selectNodeContents(fallbackEl); const s = getSelection(); s.removeAllRanges(); s.addRange(r); }
      btn.textContent = "Selected, now copy";
    }
    setTimeout(() => (btn.textContent = btn.dataset.label || "Copy message"), 2400);
  }

  /* ── Header ── */
  const menuBtn = $(".menu-btn"), menu = $("#menu");
  if (menuBtn) {
    menuBtn.addEventListener("click", () => {
      const open = menu.classList.toggle("open");
      menuBtn.setAttribute("aria-expanded", open);
    });
    document.addEventListener("keydown", e => { if (e.key === "Escape") { menu.classList.remove("open"); menuBtn.setAttribute("aria-expanded", "false"); } });
  }
  if (SHOP.whatsapp) $$("[data-wa]").forEach(el => { el.hidden = false; const a = el.matches("a") ? el : $("a", el); if (a && !a.dataset.msg) a.href = waLink(""); });

  /* ── Collection filters ── */
  const filters = $("#filters");
  if (filters) {
    const cards = $$("#grid .card");
    const setFilter = (k, push) => {
      if (!$$(".filter", filters).some(b => b.dataset.key === k)) k = "all";
      $$(".filter", filters).forEach(b => b.setAttribute("aria-pressed", b.dataset.key === k));
      cards.forEach(c => (c.hidden = !(k === "all" || c.dataset.cat.split(" ").includes(k))));
      if (push) history.replaceState(null, "", k === "all" ? location.pathname : "?show=" + k);
    };
    filters.addEventListener("click", e => { const b = e.target.closest(".filter"); if (b) setFilter(b.dataset.key, true); });
    setFilter(new URLSearchParams(location.search).get("show") || "all", false);
  }

  /* ── Look page ── */
  const lookEl = $("[data-look]");
  if (lookEl) {
    const l = LOOKS[lookEl.dataset.look];
    let size = null;
    const msgEl = $("#look-msg"), wa = $("#look-wa"), added = $("#look-added"), sizes = $("#look-sizes");
    const message = () => "Hi Blush! I'd like to enquire about " + fullName(l) + (size ? " in size " + size : "") + ". Please share the price and availability.";
    const refresh = () => { msgEl.textContent = message(); if (SHOP.whatsapp) { wa.hidden = false; wa.href = waLink(message()); } };
    sizes.addEventListener("click", e => {
      const b = e.target.closest("button"); if (!b) return;
      size = b.textContent; $$("button", sizes).forEach(x => x.setAttribute("aria-pressed", x === b));
      added.textContent = ""; refresh();
    });
    $("#look-add").addEventListener("click", () => {
      if (l.sizes.length && !size) { added.textContent = "Choose a size first."; return; }
      Bag.add(l.id, size);
      added.innerHTML = "Added to your enquiry bag. <a href=\"/bag\">View bag</a>";
    });
    $("#look-copy").addEventListener("click", e => copy(message(), e.currentTarget, msgEl));
    refresh();
  }

  /* ── Bag page ── */
  const bagRoot = $("#bag-root");
  if (bagRoot) {
    const render = () => {
      const items = Bag.read();
      if (!items.length) {
        bagRoot.innerHTML = '<div class="empty"><svg class="blossom" viewBox="0 0 24 24" fill="currentColor" style="color:var(--rose)" aria-hidden="true"><circle cx="12" cy="5.5" r="3.4"/><circle cx="18.2" cy="10" r="3.4"/><circle cx="15.8" cy="17.2" r="3.4"/><circle cx="8.2" cy="17.2" r="3.4"/><circle cx="5.8" cy="10" r="3.4"/></svg><p class="lede">Your enquiry bag is empty.</p><a class="btn" href="/collection">View the collection</a></div>';
        return;
      }
      const msg = Bag.message(items), sub = Bag.subtotal(items), n = items.reduce((a, i) => a + i.qty, 0);
      const storeReady = SHOP.mode === "store" && SHOP.checkoutUrl && sub !== null;
      bagRoot.innerHTML = '<div class="bag"><div class="bag-items">' + items.map((i, x) => {
        const l = LOOKS[i.id];
        return '<div class="bag-item"><a class="arch" href="/looks/' + l.id + '"><img src="/img/' + l.id + '-480.webp" alt="" style="object-position:' + l.pos + '"></a>' +
          '<div><h3><a href="/looks/' + l.id + '">' + esc(fullName(l)) + '</a></h3><p class="meta">' + (i.size ? "Size " + esc(i.size) : "Size on request") + '</p><p class="price">' + priceText(l) + '</p></div>' +
          '<div class="bag-ctl"><div class="qty"><button type="button" data-act="dec" data-x="' + x + '" aria-label="One fewer">–</button><span aria-live="polite">' + i.qty + '</span><button type="button" data-act="inc" data-x="' + x + '" aria-label="One more">+</button></div>' +
          '<button type="button" class="linkbtn" data-act="del" data-x="' + x + '">Remove</button></div></div>';
      }).join("") + '</div>' +
        '<aside class="preview"><span class="eyebrow">Your enquiry</span>' +
        '<div class="sum-row"><span>Pieces</span><b>' + n + '</b></div>' +
        '<div class="sum-row"><span>' + (sub !== null ? "Subtotal" : "Price") + '</span><b>' + (sub !== null ? money(sub) : "Shared on message") + '</b></div>' +
        '<div class="msg" id="bag-msg">' + esc(msg) + '</div>' +
        '<div class="dlg-cta">' +
        (storeReady ? '<a class="btn" href="' + esc(SHOP.checkoutUrl) + '">Checkout</a>' : "") +
        '<button class="btn' + (storeReady ? " ghost" : "") + '" type="button" id="bag-copy" data-label="Copy message">Copy message</button>' +
        '<a class="btn ghost" href="' + igDM + '" target="_blank" rel="noopener">Open Instagram chat</a>' +
        (SHOP.whatsapp ? '<a class="btn ghost" href="' + waLink(msg) + '" target="_blank" rel="noopener">Send on WhatsApp</a>' : "") +
        '</div><p class="hint">Copy the message, then paste it in our Instagram chat. We reply with price and availability.</p></aside></div>';
    };
    bagRoot.addEventListener("click", e => {
      const b = e.target.closest("[data-act]");
      if (b) {
        const items = Bag.read(), i = items[+b.dataset.x]; if (!i) return;
        if (b.dataset.act === "inc") i.qty = Math.min(9, i.qty + 1);
        if (b.dataset.act === "dec") i.qty -= 1;
        if (b.dataset.act === "del" || i.qty < 1) items.splice(+b.dataset.x, 1);
        Bag.write(items); render(); return;
      }
      if (e.target.id === "bag-copy") copy(Bag.message(Bag.read()), e.target, $("#bag-msg"));
    });
    render();
  }

  /* ── Contact composer ── */
  const form = $("#enquiry");
  if (form) {
    const out = $("#enq-msg"), wa = $("#enq-wa");
    const pre = new URLSearchParams(location.search).get("look");
    if (pre && LOOKS[pre]) form.look.value = pre;
    const message = () => {
      const f = form, l = LOOKS[f.look.value], parts = [];
      parts.push("Hi Blush!" + (f.name.value.trim() ? " This is " + f.name.value.trim() + "." : ""));
      parts.push(l ? "I'd like to enquire about " + fullName(l) + (f.size.value ? " in size " + f.size.value : "") + "." : "I'd like to enquire about your festive collection.");
      if (f.age.value.trim()) parts.push("My child is " + f.age.value.trim() + ".");
      if (f.date.value) parts.push("We need it by " + new Date(f.date.value + "T00:00").toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }) + ".");
      if (f.note.value.trim()) parts.push(f.note.value.trim());
      parts.push("Please share the price and availability.");
      return parts.join(" ");
    };
    const refresh = () => { out.textContent = message(); if (SHOP.whatsapp) { wa.hidden = false; wa.href = waLink(message()); } };
    form.addEventListener("input", refresh);
    form.addEventListener("submit", e => e.preventDefault());
    $("#enq-copy").addEventListener("click", e => copy(message(), e.currentTarget, out));
    refresh();
  }
})();
